"""Interactive CLI for manually driving an ALF chat session.

Usage:
    uv run python -m tools.cli <channel-url>
    uv run python -m tools.cli https://vqnol.channel.io

Optional flags:
    --headed            show the browser window (default: headless)
    --slowmo <ms>       Playwright slow-motion delay (default: 0)
    --timeout <s>       per-reply timeout (default: 60)
    --record            persist session under storage/runs/<run_id>/
    --run-id <id>       override the generated run_id (only meaningful with --record)

Sanity-check tool: type messages, see ALF replies, verify the Playwright
driver is stable before layering the scoring / scenario pipeline on top.
Empty input (just Enter) exits.

With --record, the session is written to disk under the standard storage
layout — one scenario ("interactive") with an ad-hoc scenarios.json and a
single transcript line. Useful for generating real transcripts to validate
scoring-agent before scenario generation exists.
"""

from __future__ import annotations

import argparse
import asyncio
import sys
import time

from tools.chat_driver import PlaywrightDriver
from tools.result_store import (
    SCHEMA_VERSION,
    AlfMessageRecord,
    ConfigSnapshot,
    Scenario,
    ScenarioSet,
    Transcript,
    Turn,
    append_transcript,
    new_run_id,
    utcnow_iso,
    write_config_snapshot,
    write_scenarios,
)


def _parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="tools.cli",
        description="Drive an ALF chat session interactively.",
    )
    p.add_argument("url", help="test channel URL (e.g. https://vqnol.channel.io)")
    p.add_argument(
        "--headed",
        action="store_true",
        help="show the browser window (default: headless)",
    )
    p.add_argument(
        "--slowmo",
        type=int,
        default=0,
        help="Playwright slow-motion delay in ms (default: 0)",
    )
    p.add_argument(
        "--timeout",
        type=float,
        default=60.0,
        help="per-reply timeout in seconds (default: 60)",
    )
    p.add_argument(
        "--record",
        action="store_true",
        help="persist session under storage/runs/<run_id>/",
    )
    p.add_argument(
        "--run-id",
        default=None,
        help="override generated run_id (only meaningful with --record)",
    )
    return p.parse_args(argv)


async def _read_line(prompt: str) -> str:
    """asyncio-safe stdin readline."""
    return await asyncio.get_event_loop().run_in_executor(None, input, prompt)


def _bootstrap_run(url: str, run_id: str) -> None:
    """Write initial config_snapshot + scenarios for an interactive session.

    For --record in interactive mode we don't have a real scenario set or a
    sop-agent result yet. We emit a single ad-hoc scenario ("interactive") so
    the on-disk shape matches what scoring-agent will expect downstream.
    """
    snap = ConfigSnapshot(
        schema_version=SCHEMA_VERSION,
        run_id=run_id,
        captured_at=utcnow_iso(),
        channel_url=url,
        extra={"mode": "interactive"},
    )
    write_config_snapshot(run_id, snap)

    ad_hoc = Scenario(
        id="interactive",
        intent="ad-hoc interactive session",
        persona_ref="",
        initial_message="",
        success_criteria=[],
        max_turns=0,  # uncapped in interactive mode
        source="interactive",
    )
    scenario_set = ScenarioSet(
        schema_version=SCHEMA_VERSION,
        run_id=run_id,
        scenarios=[ad_hoc],
        generated_at=utcnow_iso(),
        generation_note="generated by tools.cli --record (interactive mode)",
    )
    write_scenarios(run_id, scenario_set)


async def run(
    url: str,
    *,
    headed: bool,
    slowmo: int,
    timeout: float,
    record: bool,
    run_id_override: str | None,
) -> int:
    driver = PlaywrightDriver(headless=not headed, slow_mo_ms=slowmo)
    run_id: str | None = None
    if record:
        run_id = run_id_override or new_run_id()
        _bootstrap_run(url, run_id)
        print(f"[cli] recording to storage/runs/{run_id}/")

    print(f"[cli] opening {url} …")
    try:
        welcome = await driver.open(url)
    except Exception as exc:  # noqa: BLE001
        print(f"[cli] failed to open: {exc}", file=sys.stderr)
        await driver.close()
        return 1

    started_at = utcnow_iso()
    if welcome:
        print(f"[cli] {len(welcome)} welcome message(s) captured:")
        for m in welcome:
            print(f"  ALF: {m.text}")
    else:
        print("[cli] no welcome message detected.")

    print("[cli] ready. type a message and press Enter. empty line to quit.")

    turns: list[Turn] = []
    terminated_reason = "user_ended"
    try:
        while True:
            try:
                user_text = (await _read_line("> ")).strip()
            except (EOFError, KeyboardInterrupt):
                print()
                break
            if not user_text:
                break

            user_ts = time.time()
            await driver.send(user_text)
            try:
                replies = await driver.wait_reply(timeout=timeout)
            except TimeoutError as exc:
                print(f"[cli] timeout: {exc}", file=sys.stderr)
                if record:
                    turns.append(
                        Turn(
                            turn_index=len(turns),
                            user_message=user_text,
                            user_ts=user_ts,
                            alf_messages=[],
                            reply_latency_s=None,
                        )
                    )
                terminated_reason = "timeout"
                continue
            for reply in replies:
                print(f"ALF: {reply.text}")
            if record:
                turns.append(
                    Turn(
                        turn_index=len(turns),
                        user_message=user_text,
                        user_ts=user_ts,
                        alf_messages=[AlfMessageRecord(node_id=m.node_id, text=m.text, ts=m.ts) for m in replies],
                        reply_latency_s=replies[-1].ts - user_ts if replies else None,
                    )
                )
    finally:
        await driver.close()
        if record and run_id is not None:
            transcript = Transcript(
                schema_version=SCHEMA_VERSION,
                run_id=run_id,
                scenario_id="interactive",
                started_at=started_at,
                ended_at=utcnow_iso(),
                terminated_reason=terminated_reason,
                turns=turns,
                notes=f"welcome_messages={len(welcome)}",
            )
            append_transcript(run_id, transcript)
            print(f"[cli] wrote transcript: storage/runs/{run_id}/transcripts.jsonl")
        print("[cli] session closed.")
    return 0


def main() -> None:
    args = _parse_args(sys.argv[1:])
    sys.exit(
        asyncio.run(
            run(
                args.url,
                headed=args.headed,
                slowmo=args.slowmo,
                timeout=args.timeout,
                record=args.record,
                run_id_override=args.run_id,
            )
        )
    )


if __name__ == "__main__":
    main()
